[package]
name = "screeps-timing"
version = "0.1.0"
authors = ["William Archbell <william@archbell.com>"]
edition = "2018"

[dependencies]
scopeguard = { version = "1.0" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"